import Foundation

enum CalculatorAirports {
    static let aliases: [String: (identifier: String, label: String)] = [
        // Major airports
        "jfk": ("America/New_York", "New York JFK"),
        "lga": ("America/New_York", "New York LaGuardia"),
        "ewr": ("America/New_York", "Newark"),
        "sfo": ("America/Los_Angeles", "San Francisco"),
        "sjc": ("America/Los_Angeles", "San Jose"),
        "oak": ("America/Los_Angeles", "Oakland"),
        "lax": ("America/Los_Angeles", "Los Angeles"),
        "san": ("America/Los_Angeles", "San Diego"),
        "sea": ("America/Los_Angeles", "Seattle"),
        "pdx": ("America/Los_Angeles", "Portland"),
        "las": ("America/Los_Angeles", "Las Vegas"),
        "den": ("America/Denver", "Denver"),
        "phx": ("America/Phoenix", "Phoenix"),
        "slc": ("America/Denver", "Salt Lake City"),
        "ord": ("America/Chicago", "Chicago O'Hare"),
        "mdw": ("America/Chicago", "Chicago Midway"),
        "dfw": ("America/Chicago", "Dallas/Fort Worth"),
        "iah": ("America/Chicago", "Houston Intercontinental"),
        "hou": ("America/Chicago", "Houston Hobby"),
        "atl": ("America/New_York", "Atlanta"),
        "mia": ("America/New_York", "Miami"),
        "mco": ("America/New_York", "Orlando"),
        "tpa": ("America/New_York", "Tampa"),
        "bos": ("America/New_York", "Boston"),
        "iad": ("America/New_York", "Washington Dulles"),
        "dca": ("America/New_York", "Washington Reagan"),
        "bwi": ("America/New_York", "Baltimore"),
        "phl": ("America/New_York", "Philadelphia"),
        "msp": ("America/Chicago", "Minneapolis"),
        "dtw": ("America/Detroit", "Detroit"),
        "clt": ("America/New_York", "Charlotte"),
        "aus": ("America/Chicago", "Austin"),
        "bna": ("America/Chicago", "Nashville"),
        "msy": ("America/Chicago", "New Orleans"),
        "lhr": ("Europe/London", "London Heathrow"),
        "lgw": ("Europe/London", "London Gatwick"),
        "stn": ("Europe/London", "London Stansted"),
        "man": ("Europe/London", "Manchester"),
        "edi": ("Europe/London", "Edinburgh"),
        "cdg": ("Europe/Paris", "Paris CDG"),
        "ory": ("Europe/Paris", "Paris Orly"),
        "fra": ("Europe/Berlin", "Frankfurt"),
        "muc": ("Europe/Berlin", "Munich"),
        "ber": ("Europe/Berlin", "Berlin"),
        "ams": ("Europe/Amsterdam", "Amsterdam"),
        "mad": ("Europe/Madrid", "Madrid"),
        "bcn": ("Europe/Madrid", "Barcelona"),
        "fco": ("Europe/Rome", "Rome Fiumicino"),
        "mxp": ("Europe/Rome", "Milan Malpensa"),
        "zrh": ("Europe/Zurich", "Zurich"),
        "gva": ("Europe/Zurich", "Geneva"),
        "vie": ("Europe/Vienna", "Vienna"),
        "arn": ("Europe/Stockholm", "Stockholm"),
        "cph": ("Europe/Copenhagen", "Copenhagen"),
        "osl": ("Europe/Oslo", "Oslo"),
        "hel": ("Europe/Helsinki", "Helsinki"),
        "dub": ("Europe/Dublin", "Dublin"),
        "bru": ("Europe/Brussels", "Brussels"),
        "lis": ("Europe/Lisbon", "Lisbon"),
        "ath": ("Europe/Athens", "Athens"),
        "waw": ("Europe/Warsaw", "Warsaw"),
        "prg": ("Europe/Prague", "Prague"),
        "bud": ("Europe/Budapest", "Budapest"),
        "istanbul": ("Europe/Istanbul", "Istanbul"),
        "hnd": ("Asia/Tokyo", "Tokyo Haneda"),
        "nrt": ("Asia/Tokyo", "Tokyo Narita"),
        "kix": ("Asia/Tokyo", "Osaka Kansai"),
        "icn": ("Asia/Seoul", "Seoul Incheon"),
        "pvg": ("Asia/Shanghai", "Shanghai Pudong"),
        "pek": ("Asia/Shanghai", "Beijing Capital"),
        "can": ("Asia/Shanghai", "Guangzhou"),
        "hkg": ("Asia/Hong_Kong", "Hong Kong"),
        "tpe": ("Asia/Taipei", "Taipei"),
        "sin": ("Asia/Singapore", "Singapore"),
        "kul": ("Asia/Kuala_Lumpur", "Kuala Lumpur"),
        "bkk": ("Asia/Bangkok", "Bangkok"),
        "cgk": ("Asia/Jakarta", "Jakarta"),
        "mnl": ("Asia/Manila", "Manila"),
        "del": ("Asia/Kolkata", "Delhi"),
        "bom": ("Asia/Kolkata", "Mumbai"),
        "blr": ("Asia/Kolkata", "Bengaluru"),
        "maa": ("Asia/Kolkata", "Chennai"),
        "hyd": ("Asia/Kolkata", "Hyderabad"),
        "ccu": ("Asia/Kolkata", "Kolkata"),
        "dxb": ("Asia/Dubai", "Dubai"),
        "auh": ("Asia/Dubai", "Abu Dhabi"),
        "doh": ("Asia/Qatar", "Doha"),
        "ruh": ("Asia/Riyadh", "Riyadh"),
        "jed": ("Asia/Riyadh", "Jeddah"),
        "syd": ("Australia/Sydney", "Sydney"),
        "mel": ("Australia/Melbourne", "Melbourne"),
        "bne": ("Australia/Brisbane", "Brisbane"),
        "per": ("Australia/Perth", "Perth"),
        "adl": ("Australia/Adelaide", "Adelaide"),
        "akl": ("Pacific/Auckland", "Auckland"),
        "yyz": ("America/Toronto", "Toronto"),
        "yul": ("America/Montreal", "Montreal"),
        "yvr": ("America/Vancouver", "Vancouver"),
        "mex": ("America/Mexico_City", "Mexico City"),
        "gru": ("America/Sao_Paulo", "São Paulo"),
        "gig": ("America/Sao_Paulo", "Rio de Janeiro"),
        "eze": ("America/Argentina/Buenos_Aires", "Buenos Aires"),
        "scl": ("America/Santiago", "Santiago"),
        "bog": ("America/Bogota", "Bogotá"),
        "lim": ("America/Lima", "Lima"),
        "jnb": ("Africa/Johannesburg", "Johannesburg"),
        "cpt": ("Africa/Johannesburg", "Cape Town"),
        "cai": ("Africa/Cairo", "Cairo"),
        "nbo": ("Africa/Nairobi", "Nairobi"),
        "los": ("Africa/Lagos", "Lagos"),

        // City nicknames
        "sf": ("America/Los_Angeles", "San Francisco"),
        "san francisco": ("America/Los_Angeles", "San Francisco"),
        "nyc": ("America/New_York", "New York City"),
        "new york city": ("America/New_York", "New York City"),
        "ldn": ("Europe/London", "London"),
        "london uk": ("Europe/London", "London"),
        "united kingdom": ("Europe/London", "United Kingdom"),
        "bombay": ("Asia/Kolkata", "Mumbai"),
        "mumbai": ("Asia/Kolkata", "Mumbai"),
        "bangalore": ("Asia/Kolkata", "Bengaluru"),
        "bengaluru": ("Asia/Kolkata", "Bengaluru"),
        "calcutta": ("Asia/Kolkata", "Kolkata"),
        "kolkata": ("Asia/Kolkata", "Kolkata"),
        "peking": ("Asia/Shanghai", "Beijing"),
        "dc": ("America/New_York", "Washington DC"),
        "washington": ("America/New_York", "Washington DC"),
        "la": ("America/Los_Angeles", "Los Angeles"),
        "los angeles": ("America/Los_Angeles", "Los Angeles"),
    ]
}
